alias: sunscreen
description: check to see if sunscreen action is required
trigger:
  - platform: state
    entity_id:
      - timer.sunscreen_delay
    from: active
    to: idle
  - platform: state
    entity_id:
      - binary_sensor.sunscreen_criteria
    to: "off"
  - platform: state
    entity_id:
      - binary_sensor.sunscreen_criteria
    to: "on"
condition: []
action:
  - choose:
      - conditions:
          - condition: template
            value_template: >-
              {{ states('binary_sensor.sunscreen_criteria') !=
              states('input_boolean.sunscreen_status') }}
        sequence: null
      - conditions:
          - condition: state
            entity_id: input_boolean.sunscreen_manual
            state: active
          - condition: state
            entity_id: binary_sensor.sunscreen_criteria_critical
            state: "off"
        sequence: []
    default:
      - if:
          - condition: state
            entity_id: binary_sensor.sunscreen_criteria
            state: "off"
        then:
          - service: cover.close_cover
            target:
              entity_id:
                - cover.zonnescherm
            data: {}
            enabled: true
          - service: input_boolean.turn_on
            target:
              entity_id:
                - input_boolean.sunscreen_status
            data: {}
        else:
          - service: cover.open_cover
            target:
              entity_id:
                - cover.zonnescherm
            data: {}
            enabled: true
          - service: input_boolean.turn_off
            target:
              entity_id:
                - input_boolean.sunscreen_status
            data: {}
      - service: timer.start
        data:
          duration: "00:30:00"
        target:
          entity_id: timer.sunscreen_delay
      - delay:
          hours: 0
          minutes: 0
          seconds: 15
          milliseconds: 0
        enabled: true
mode: single
